VERSION="2.2.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GAUTG3WJGV54WJF3ZBNWNSFD73YV7YVBKUN54DW3LQY7RUO57ADIDITX"]

[DOCUMENTATION]
ORG_NAME="Stellar Token Marketplace"
ORG_URL="https://xlmtoken.github.io"

# Stellar TOML Home Domain: xlmtoken.github.io

[[CURRENCIES]]
code="ITX"
issuer="GAUTG3WJGV54WJF3ZBNWNSFD73YV7YVBKUN54DW3LQY7RUO57ADIDITX"
display_decimals=7
is_asset_anchored=false
name="Internet Technology Xenogeny"
desc="production of an offspring entirely different from either of the parents. — xenogenetic, xenogenic"
conditions="not limited or restricted in terms of number, quantity, or extent"
image="https://xlmtoken.github.io/itx.jpg"

# ITX Token
